import type { EnglishLevel } from './types';

export const LEVEL_4: EnglishLevel = {
  id: 4,
  name: 'Kalimat Panjang',
  desc: 'Kalimat panjang dan kaya kata',
  vocab: [
    { en: 'farmer', id: 'petani', emoji: '🧑‍🌾' },
    { en: 'doctor', id: 'dokter', emoji: '🧑‍⚕️' },
    { en: 'nurse', id: 'perawat', emoji: '👩‍⚕️' },
    { en: 'police officer', id: 'polisi', emoji: '👮' },
    { en: 'driver', id: 'pengemudi', emoji: '🚕' },
    { en: 'airplane', id: 'pesawat', emoji: '✈️' },
    { en: 'ship', id: 'kapal', emoji: '🚢' },
    { en: 'umbrella', id: 'payung', emoji: '☂️' },
    { en: 'shoes', id: 'sepatu', emoji: '👟' },
    { en: 'hat', id: 'topi', emoji: '🎩' },
    { en: 'window', id: 'jendela', emoji: '🪟' },
    { en: 'door', id: 'pintu', emoji: '🚪' },
    { en: 'clock', id: 'jam', emoji: '⏰' },
    { en: 'mirror', id: 'cermin', emoji: '🪞' },
    { en: 'key', id: 'kunci', emoji: '🔑' },
    { en: 'money', id: 'uang', emoji: '💰' },
    { en: 'bridge', id: 'jembatan', emoji: '🌉' },
    { en: 'river', id: 'sungai', emoji: '🏞️' },
    { en: 'lawyer', id: 'pengacara', emoji: '🧑‍⚖️' },
    { en: 'dentist', id: 'dokter gigi', emoji: '🦷' },
    { en: 'soldier', id: 'tentara', emoji: '🪖' },
    { en: 'engineer', id: 'insinyur', emoji: '🧑‍💻' },
    { en: 'hammer', id: 'palu', emoji: '🔨' },
    { en: 'saw', id: 'gergaji', emoji: '🪚' },
    { en: 'needle', id: 'jarum', emoji: '🪡' },
    { en: 'rope', id: 'tali', emoji: '🪢' },
    { en: 'ladder', id: 'tangga', emoji: '🪜' },
    { en: 'bucket', id: 'ember', emoji: '🪣' },
    { en: 'torch', id: 'senter', emoji: '🔦' },
    { en: 'battery', id: 'baterai', emoji: '🔋' },
    { en: 'envelope', id: 'amplop', emoji: '✉️' },
    { en: 'stamp', id: 'perangko', emoji: '📮' },
    { en: 'suitcase', id: 'koper', emoji: '🧳' },
    { en: 'telescope', id: 'teleskop', emoji: '🔭' },
    { en: 'microscope', id: 'mikroskop', emoji: '🔬' },
    { en: 'globe', id: 'bola dunia', emoji: '🌍' },
    { en: 'compass', id: 'kompas', emoji: '🧭' },
    { en: 'medal', id: 'medali', emoji: '🥇' },
    { en: 'crown', id: 'mahkota', emoji: '👑' },
    { en: 'castle', id: 'kastil', emoji: '🏰' },
  ],
  sentences: [
    { en: 'I go to school every morning', id: 'Saya pergi ke sekolah setiap pagi' },
    { en: 'She likes to eat big red apples', id: 'Dia suka makan apel merah besar' },
    { en: 'We played ball in the park yesterday', id: 'Kami bermain bola di taman kemarin' },
    { en: 'Mother cooks fried rice for father', id: 'Ibu memasak nasi goreng untuk ayah' },
    { en: 'The small cat sleeps on the chair', id: 'Kucing kecil itu tidur di kursi' },
    { en: 'I study English every day', id: 'Saya belajar bahasa Inggris setiap hari' },
    { en: 'They go to the beach on Sunday', id: 'Mereka pergi ke pantai pada hari Minggu' },
    { en: 'Father buys three new books for me', id: 'Ayah membeli tiga buku baru untukku' },
    { en: "Every morning I wake up at six o'clock", id: 'Setiap pagi saya bangun pukul enam' },
    { en: 'After breakfast I go to school with my sister', id: 'Setelah sarapan saya pergi ke sekolah bersama kakak saya' },
    { en: 'My mother prepares breakfast for the whole family', id: 'Ibu saya menyiapkan sarapan untuk seluruh keluarga' },
    { en: 'My father reads the newspaper before work', id: 'Ayah saya membaca koran sebelum bekerja' },
    { en: 'We always brush our teeth before bed', id: 'Kami selalu menyikat gigi sebelum tidur' },
    { en: 'The students listen carefully to the teacher', id: 'Murid-murid mendengarkan guru dengan saksama' },
    { en: 'I finish my homework before dinner', id: 'Saya menyelesaikan PR sebelum makan malam' },
    { en: 'She helps her mother wash the dishes', id: 'Dia membantu ibunya mencuci piring' },
    { en: 'He cleans his bicycle every weekend', id: 'Dia membersihkan sepedanya setiap akhir pekan' },
    { en: 'We visit our grandparents on the weekend', id: 'Kami mengunjungi kakek dan nenek saat akhir pekan' },
    { en: 'My grandmother tells us a funny story', id: 'Nenek saya menceritakan kisah lucu kepada kami' },
    { en: 'The children play hide and seek in the garden', id: 'Anak-anak bermain petak umpet di kebun' },
    { en: 'The cat hides under the table when it rains', id: 'Kucing itu bersembunyi di bawah meja saat hujan' },
    { en: 'My dog likes to run in the garden', id: 'Anjing saya suka berlari di kebun' },
    { en: 'The rabbit eats carrots and green vegetables', id: 'Kelinci itu makan wortel dan sayuran hijau' },
    { en: 'We keep the milk in the refrigerator', id: 'Kami menyimpan susu di kulkas' },
    { en: 'She pours a cup of hot tea', id: 'Dia menuang secangkir teh panas' },
    { en: 'He puts sugar and milk in his coffee', id: 'Dia menambahkan gula dan susu ke kopinya' },
    { en: 'The baker makes fresh bread every morning', id: 'Tukang roti membuat roti segar setiap pagi' },
    { en: 'The market sells fruits and vegetables', id: 'Pasar itu menjual buah dan sayur' },
    { en: 'I bring a bottle of water to school', id: 'Saya membawa sebotol air ke sekolah' },
    { en: 'My father buys fresh fruit at the market', id: 'Ayah saya membeli buah segar di pasar' },
    { en: 'She always feeds the chickens in the morning', id: 'Dia selalu memberi makan ayam di pagi hari' },
    { en: 'The farmer works hard in the rice field', id: 'Petani itu bekerja keras di sawah' },
    { en: 'The fisherman catches fish with his net', id: 'Nelayan itu menangkap ikan dengan jaringnya' },
    { en: 'We learn many new words from the dictionary', id: 'Kami mempelajari banyak kata baru dari kamus' },
    { en: 'The teacher explains the lesson with a picture', id: 'Guru menjelaskan pelajaran dengan gambar' },
    { en: 'I raise my hand before I speak', id: 'Saya mengangkat tangan sebelum berbicara' },
    { en: 'She answers the question correctly', id: 'Dia menjawab pertanyaan dengan benar' },
    { en: 'We do our homework in the living room', id: 'Kami mengerjakan PR di ruang tamu' },
    { en: 'He fixes his bicycle with a small tool', id: 'Dia memperbaiki sepedanya dengan alat kecil' },
    { en: 'The mechanic repairs the old car', id: 'Montir itu memperbaiki mobil tua' },
    { en: 'My uncle drives a taxi in the city', id: 'Paman saya mengemudikan taksi di kota' },
    { en: 'The bus arrives at the station on time', id: 'Bus itu tiba di stasiun tepat waktu' },
    { en: 'The train travels through the green mountains', id: 'Kereta itu melewati pegunungan hijau' },
    { en: 'The airplane flies high above the clouds', id: 'Pesawat itu terbang tinggi di atas awan' },
    { en: 'The ship sails across the blue sea', id: 'Kapal itu berlayar melintasi laut biru' },
    { en: 'The helicopter lands on the hospital roof', id: 'Helikopter itu mendarat di atap rumah sakit' },
    { en: 'The firefighter climbs the ladder quickly', id: 'Pemadam kebakaran itu memanjat tangga dengan cepat' },
    { en: 'The police officer directs the traffic', id: 'Polisi itu mengatur lalu lintas' },
    { en: 'The doctor checks the patient carefully', id: 'Dokter itu memeriksa pasien dengan teliti' },
    { en: 'The nurse gives medicine to the patient', id: 'Perawat itu memberikan obat kepada pasien' },
    { en: 'My aunt works as a nurse at the hospital', id: 'Bibi saya bekerja sebagai perawat di rumah sakit' },
    { en: 'The dentist fixes my tooth', id: 'Dokter gigi menambal gigi saya' },
    { en: 'The lawyer reads the important paper', id: 'Pengacara itu membaca dokumen penting' },
    { en: 'The soldier stands in front of the gate', id: 'Tentara itu berdiri di depan gerbang' },
    { en: 'The engineer builds a strong bridge', id: 'Insinyur itu membangun jembatan yang kuat' },
    { en: 'The artist paints a beautiful landscape', id: 'Seniman itu melukis pemandangan yang indah' },
    { en: 'The singer performs on a big stage', id: 'Penyanyi itu tampil di panggung besar' },
    { en: 'The scientist looks through the microscope', id: 'Ilmuwan itu melihat melalui mikroskop' },
    { en: 'The astronaut travels to the moon', id: 'Astronaut itu pergi ke bulan' },
    { en: 'The pilot wears a white hat', id: 'Pilot itu memakai topi putih' },
    { en: 'We take a photo near the fountain', id: 'Kami mengambil foto di dekat air mancur' },
    { en: 'The family photo hangs near the door', id: 'Foto keluarga itu tergantung di dekat pintu' },
    { en: 'There is a mirror on the wall', id: 'Ada cermin di dinding' },
    { en: 'Fresh air comes through the open window', id: 'Udara segar masuk melalui jendela yang terbuka' },
    { en: 'Please close the window before you leave', id: 'Tolong tutup jendela sebelum kamu pergi' },
    { en: "The clock on the wall shows nine o'clock", id: 'Jam di dinding menunjukkan pukul sembilan' },
    { en: 'The key opens the wooden door', id: 'Kunci itu membuka pintu kayu' },
    { en: 'He keeps his money in a small wallet', id: 'Dia menyimpan uangnya di dompet kecil' },
    { en: 'My mother puts the flowers in a vase', id: 'Ibu saya menaruh bunga di vas' },
    { en: 'The vase is made of glass', id: 'Vas itu terbuat dari kaca' },
    { en: 'We eat dinner around the big table', id: 'Kami makan malam mengelilingi meja besar' },
    { en: 'The soup tastes a little salty', id: 'Supnya terasa sedikit asin' },
    { en: 'She adds salt and pepper to the soup', id: 'Dia menambahkan garam dan merica ke sup' },
    { en: 'I drink a glass of fresh milk', id: 'Saya minum segelas susu segar' },
    { en: 'The orange juice is very sweet', id: 'Jus jeruknya sangat manis' },
    { en: 'We bake a chocolate cake together', id: 'Kami memanggang kue cokelat bersama' },
    { en: 'My brother loves ice cream and cookies', id: 'Kakak saya suka es krim dan biskuit' },
    { en: 'The candy shop is near the school', id: 'Toko permen itu dekat sekolah' },
    { en: 'I eat an apple every day', id: 'Saya makan apel setiap hari' },
    { en: 'We plant vegetables in the garden', id: 'Kami menanam sayur di kebun' },
    { en: 'The garden is full of colorful flowers', id: 'Kebun itu penuh bunga berwarna-warni' },
    { en: 'The butterfly lands on the yellow flower', id: 'Kupu-kupu itu hinggap di bunga kuning' },
    { en: 'The bee flies from flower to flower', id: 'Lebah itu terbang dari bunga ke bunga' },
    { en: 'The bird builds a nest in the tree', id: 'Burung itu membuat sarang di pohon' },
    { en: 'The squirrel hides nuts in the ground', id: 'Tupai itu menyembunyikan kacang di tanah' },
    { en: 'The frog jumps into the pond', id: 'Katak itu melompat ke kolam' },
    { en: 'The duck swims on the lake', id: 'Bebek itu berenang di danau' },
    { en: 'The fish swims in the clear water', id: 'Ikan itu berenang di air yang jernih' },
    { en: 'The turtle walks slowly on the sand', id: 'Kura-kura itu berjalan lambat di pasir' },
    { en: 'The crab hides under the rock', id: 'Kepiting itu bersembunyi di bawah batu' },
    { en: 'The whale is the biggest animal in the sea', id: 'Paus adalah hewan terbesar di laut' },
    { en: 'The dolphin jumps out of the water', id: 'Lumba-lumba itu melompat keluar dari air' },
    { en: 'The elephant has a long trunk', id: 'Gajah itu punya belalai panjang' },
    { en: 'The giraffe has a very long neck', id: 'Jerapah itu punya leher yang sangat panjang' },
    { en: 'The monkey climbs the tall tree', id: 'Monyet itu memanjat pohon tinggi' },
    { en: 'The lion is the king of the jungle', id: 'Singa adalah raja hutan' },
    { en: 'The tiger has beautiful orange fur', id: 'Harimau itu punya bulu oranye yang indah' },
    { en: 'The bear sleeps in a cave all winter', id: 'Beruang itu tidur di gua sepanjang musim dingin' },
    { en: 'The snake moves quietly through the grass', id: 'Ular itu bergerak diam-diam di rumput' },
    { en: 'The butterfly has colorful wings', id: 'Kupu-kupu itu punya sayap berwarna-warni' },
    { en: 'The ant carries food to its nest', id: 'Semut itu membawa makanan ke sarangnya' },
    { en: 'The spider makes a web in the corner', id: 'Laba-laba itu membuat jaring di sudut' },
    { en: 'The mouse runs into a small hole', id: 'Tikus itu berlari masuk ke lubang kecil' },
    { en: 'The horse runs fast in the field', id: 'Kuda itu berlari cepat di lapangan' },
    { en: 'The goat eats grass on the hill', id: 'Kambing itu makan rumput di bukit' },
    { en: 'The cow gives us fresh milk', id: 'Sapi itu memberi kami susu segar' },
    { en: 'The chicken lays an egg every day', id: 'Ayam itu bertelur setiap hari' },
    { en: 'The rooster crows early in the morning', id: 'Ayam jago berkokok pagi-pagi' },
    { en: 'We visit the zoo with our class', id: 'Kami mengunjungi kebun binatang bersama kelas' },
    { en: 'The zookeeper feeds the hungry animals', id: 'Penjaga kebun binatang memberi makan hewan yang lapar' },
    { en: 'The panda eats bamboo leaves', id: 'Panda itu makan daun bambu' },
    { en: 'The kangaroo carries its baby in a pouch', id: 'Kangguru membawa bayinya di kantong' },
    { en: 'The penguin lives in a very cold place', id: 'Penguin hidup di tempat yang sangat dingin' },
    { en: 'The camel walks across the hot desert', id: 'Unta itu berjalan melintasi gurun panas' },
    { en: 'The owl sleeps during the day', id: 'Burung hantu tidur pada siang hari' },
    { en: 'The eagle flies high in the sky', id: 'Elang itu terbang tinggi di langit' },
    { en: 'The shark has sharp white teeth', id: 'Hiu itu punya gigi putih yang tajam' },
    { en: 'The octopus has eight long arms', id: 'Gurita itu punya delapan lengan panjang' },
    { en: 'The snail carries its house on its back', id: 'Siput membawa rumahnya di punggung' },
    { en: 'We collect shells on the beach', id: 'Kami mengumpulkan kerang di pantai' },
    { en: 'I build a sand castle on the beach', id: 'Saya membangun istana pasir di pantai' },
    { en: 'We swim in the warm sea', id: 'Kami berenang di laut yang hangat' },
    { en: 'The sun sets behind the mountain', id: 'Matahari terbenam di balik gunung' },
    { en: 'The moon and stars light the night sky', id: 'Bulan dan bintang menerangi langit malam' },
    { en: 'The sky turns orange in the evening', id: 'Langit berubah oranye pada sore hari' },
    { en: 'The rain stops after a few minutes', id: 'Hujan berhenti setelah beberapa menit' },
    { en: 'The wind blows the leaves off the trees', id: 'Angin meniup daun-daun dari pohon' },
    { en: 'The snow covers the whole village', id: 'Salju menutupi seluruh desa' },
    { en: 'The rainbow appears after the rain', id: 'Pelangi muncul setelah hujan' },
    { en: 'The river flows quietly through the village', id: 'Sungai itu mengalir tenang melewati desa' },
    { en: 'The lake is deep and very cold', id: 'Danau itu dalam dan sangat dingin' },
    { en: 'The forest is home to many animals', id: 'Hutan adalah rumah bagi banyak hewan' },
    { en: 'The island has a beautiful white beach', id: 'Pulau itu punya pantai putih yang indah' },
    { en: 'The volcano erupts with fire and smoke', id: 'Gunung berapi itu meletus dengan api dan asap' },
    { en: 'The waterfall falls from a high cliff', id: 'Air terjun itu jatuh dari tebing tinggi' },
    { en: 'We climb the mountain on Saturday', id: 'Kami mendaki gunung pada hari Sabtu' },
    { en: 'We walk along the rice field path', id: 'Kami berjalan di sepanjang pematang sawah' },
    { en: 'The village is small and peaceful', id: 'Desa itu kecil dan damai' },
    { en: 'The city is busy and noisy', id: 'Kota itu sibuk dan berisik' },
    { en: 'Many people work in the big city', id: 'Banyak orang bekerja di kota besar' },
    { en: 'The market is crowded on Sunday morning', id: 'Pasar itu ramai pada Minggu pagi' },
    { en: 'The shop sells bread and fresh milk', id: 'Toko itu menjual roti dan susu segar' },
    { en: 'The restaurant serves rice and noodles', id: 'Restoran itu menyajikan nasi dan mie' },
    { en: 'We order fried rice and orange juice', id: 'Kami memesan nasi goreng dan jus jeruk' },
    { en: 'My father pays the bill after dinner', id: 'Ayah saya membayar tagihan setelah makan malam' },
    { en: 'I help my mother set the table', id: 'Saya membantu ibu menata meja' },
    { en: 'She washes the dishes after dinner', id: 'Dia mencuci piring setelah makan malam' },
    { en: 'He wipes the table after dinner', id: 'Dia mengelap meja setelah makan malam' },
    { en: 'The trash bin is full of paper', id: 'Tempat sampah itu penuh kertas' },
    { en: 'The room is clean and tidy now', id: 'Kamarnya bersih dan rapi sekarang' },
    { en: 'I make my bed every morning', id: 'Saya merapikan tempat tidur setiap pagi' },
    { en: 'My clothes are in the wooden closet', id: 'Pakaian saya ada di lemari kayu' },
    { en: 'She folds the clean clothes neatly', id: 'Dia melipat pakaian bersih dengan rapi' },
    { en: 'He wears a blue shirt and black pants', id: 'Dia memakai kemeja biru dan celana hitam' },
    { en: 'My sister wears a pretty red dress', id: 'Kakak saya memakai gaun merah yang cantik' },
    { en: 'We wear warm jackets in the winter', id: 'Kami memakai jaket hangat di musim dingin' },
    { en: 'I put on my socks and shoes', id: 'Saya memakai kaus kaki dan sepatu' },
    { en: 'The umbrella protects us from the rain', id: 'Payung melindungi kami dari hujan' },
    { en: 'My boots are dirty from the mud', id: 'Sepatu bot saya kotor karena lumpur' },
    { en: 'We walk to school together every day', id: 'Kami berjalan ke sekolah bersama setiap hari' },
    { en: 'The school is not far from my house', id: 'Sekolahnya tidak jauh dari rumah saya' },
    { en: 'My classroom has a big white board', id: 'Kelasku punya papan tulis putih yang besar' },
    { en: 'The students sit in neat rows', id: 'Murid-murid duduk dalam barisan rapi' },
    { en: 'The teacher gives us a new lesson', id: 'Guru memberi kami pelajaran baru' },
    { en: 'We read a story about a brave knight', id: 'Kami membaca cerita tentang ksatria pemberani' },
    { en: 'I write my name on the paper', id: 'Saya menulis nama saya di kertas' },
    { en: 'She colors the drawing with crayons', id: 'Dia mewarnai gambarnya dengan krayon' },
    { en: 'We sing the national anthem together', id: 'Kami menyanyikan lagu kebangsaan bersama' },
    { en: 'The bell rings at the end of class', id: 'Bel berbunyi di akhir pelajaran' },
    { en: 'We play football after school', id: 'Kami bermain sepak bola setelah sekolah' },
    { en: 'My friend kicks the ball into the goal', id: 'Teman saya menendang bola ke gawang' },
    { en: 'The team wins the game today', id: 'Tim itu memenangkan pertandingan hari ini' },
    { en: 'The coach teaches us how to play', id: 'Pelatih mengajari kami cara bermain' },
    { en: 'We practice every Tuesday and Thursday', id: 'Kami berlatih setiap Selasa dan Kamis' },
    { en: 'I ride my bicycle to the shop', id: 'Saya mengendarai sepeda ke toko' },
    { en: 'We run across the wide field', id: 'Kami berlari melintasi lapangan yang luas' },
    { en: 'We have a picnic under the big tree', id: 'Kami piknik di bawah pohon besar' },
    { en: 'My mother brings sandwiches and juice', id: 'Ibu saya membawa roti isi dan jus' },
    { en: 'The little bird sits on the branch', id: 'Burung kecil itu duduk di dahan' },
    { en: 'The cat naps in the warm sun', id: 'Kucing itu tidur-tiduran di matahari hangat' },
    { en: 'The dog wags its tail happily', id: 'Anjing itu mengibaskan ekornya dengan senang' },
    { en: 'My rabbit has soft white fur', id: 'Kelinci saya punya bulu putih yang lembut' },
    { en: 'I give my pet fresh water every day', id: 'Saya memberi hewan peliharaan saya air segar setiap hari' },
    { en: 'We take our dog for a walk', id: 'Kami mengajak anjing kami berjalan-jalan' },
    { en: 'The kitten plays with a ball of yarn', id: 'Anak kucing itu bermain dengan bola benang' },
    { en: 'My grandmother knits a warm scarf', id: 'Nenek saya merajut syal yang hangat' },
    { en: 'My grandfather tells stories about the past', id: 'Kakek saya menceritakan kisah masa lalu' },
    { en: 'We celebrate my birthday with a cake', id: 'Kami merayakan ulang tahun saya dengan kue' },
    { en: 'We invite our friends to the party', id: 'Kami mengundang teman-teman ke pesta' },
    { en: 'They give me a nice birthday gift', id: 'Mereka memberiku hadiah ulang tahun yang bagus' },
    { en: 'I blow out the candles on the cake', id: 'Saya meniup lilin di atas kue' },
    { en: 'We take many photos at the party', id: 'Kami mengambil banyak foto di pesta' },
    { en: 'The music is loud and cheerful', id: 'Musiknya keras dan ceria' },
    { en: 'We dance and sing together', id: 'Kami menari dan bernyanyi bersama' },
    { en: 'Everyone laughs at the silly clown tricks', id: 'Semua orang tertawa melihat tingkah lucu badut' },
    { en: 'The clown wears a colorful hat', id: 'Badut itu memakai topi berwarna-warni' },
    { en: 'I feel happy and excited today', id: 'Saya merasa senang dan bersemangat hari ini' },
    { en: 'She feels proud of her hard work', id: 'Dia merasa bangga atas kerja kerasnya' },
    { en: 'He feels tired after the long trip', id: 'Dia merasa lelah setelah perjalanan panjang' },
    { en: 'The baby laughs at the funny toy', id: 'Bayi itu tertawa melihat mainan lucu' },
    { en: 'My mother sings a soft lullaby', id: 'Ibu saya menyanyikan lagu pengantar tidur yang lembut' },
    { en: 'The night is calm and quiet', id: 'Malamnya tenang dan damai' },
    { en: 'I wash my face before bed', id: 'Saya mencuci muka sebelum tidur' },
    { en: 'I say good night to my parents', id: 'Saya mengucapkan selamat malam kepada orang tua saya' },
    { en: 'I read a book before I sleep', id: 'Saya membaca buku sebelum tidur' },
    { en: 'The stars shine brightly at night', id: 'Bintang-bintang bersinar terang di malam hari' },
    { en: 'Tomorrow we will visit the museum', id: 'Besok kami akan mengunjungi museum' },
    { en: 'Next week we will go to the beach', id: 'Minggu depan kami akan pergi ke pantai' },
    { en: 'I hope the weather is sunny tomorrow', id: 'Saya harap cuacanya cerah besok' },
    { en: 'We always have fun together', id: 'Kami selalu bersenang-senang bersama' },
  ],
};
