import type { EnglishLevel } from './types';

export const LEVEL_3: EnglishLevel = {
  id: 3,
  name: 'Kalimat',
  desc: 'Kalimat pendek sehari-hari tentang tempat dan aktivitas',
  vocab: [
    { en: 'school', id: 'sekolah', emoji: '🏫' },
    { en: 'teacher', id: 'guru', emoji: '🧑‍🏫' },
    { en: 'student', id: 'murid', emoji: '🧑‍🎓' },
    { en: 'hospital', id: 'rumah sakit', emoji: '🏥' },
    { en: 'market', id: 'pasar', emoji: '🏪' },
    { en: 'rice', id: 'nasi', emoji: '🍚' },
    { en: 'water', id: 'air', emoji: '💧' },
    { en: 'milk', id: 'susu', emoji: '🥛' },
    { en: 'egg', id: 'telur', emoji: '🥚' },
    { en: 'bread', id: 'roti', emoji: '🍞' },
    { en: 'mountain', id: 'gunung', emoji: '⛰️' },
    { en: 'beach', id: 'pantai', emoji: '🏖️' },
    { en: 'city', id: 'kota', emoji: '🏙️' },
    { en: 'village', id: 'desa', emoji: '🏘️' },
    { en: 'garden', id: 'kebun', emoji: '🌳' },
    { en: 'kitchen', id: 'dapur', emoji: '🍳' },
    { en: 'bedroom', id: 'kamar tidur', emoji: '🛏️' },
    { en: 'bicycle', id: 'sepeda', emoji: '🚲' },
    { en: 'car', id: 'mobil', emoji: '🚗' },
    { en: 'train', id: 'kereta', emoji: '🚆' },
    { en: 'bathroom', id: 'kamar mandi', emoji: '🚿' },
    { en: 'living room', id: 'ruang tamu', emoji: '🛋️' },
    { en: 'dining room', id: 'ruang makan', emoji: '🍽️' },
    { en: 'garage', id: 'garasi', emoji: '🚙' },
    { en: 'roof', id: 'atap', emoji: '🏠' },
    { en: 'wall', id: 'dinding', emoji: '🧱' },
    { en: 'stairs', id: 'tangga', emoji: '🪜' },
    { en: 'yard', id: 'halaman', emoji: '🌳' },
    { en: 'gate', id: 'gerbang', emoji: '🚧' },
    { en: 'bank', id: 'bank', emoji: '🏦' },
    { en: 'mosque', id: 'masjid', emoji: '🕌' },
    { en: 'church', id: 'gereja', emoji: '⛪' },
    { en: 'temple', id: 'pura', emoji: '🛕' },
    { en: 'library', id: 'perpustakaan', emoji: '📚' },
    { en: 'museum', id: 'museum', emoji: '🏛️' },
    { en: 'restaurant', id: 'restoran', emoji: '🍽️' },
    { en: 'park', id: 'taman', emoji: '🏞️' },
    { en: 'airport', id: 'bandara', emoji: '✈️' },
    { en: 'station', id: 'stasiun', emoji: '🚉' },
    { en: 'port', id: 'pelabuhan', emoji: '⚓' },
    { en: 'post office', id: 'kantor pos', emoji: '📮' },
    { en: 'zoo', id: 'kebun binatang', emoji: '🦁' },
    { en: 'farm', id: 'peternakan', emoji: '🌾' },
    { en: 'field', id: 'sawah', emoji: '🌾' },
    { en: 'forest', id: 'hutan', emoji: '🌲' },
    { en: 'island', id: 'pulau', emoji: '🏝️' },
    { en: 'lake', id: 'danau', emoji: '🏞️' },
    { en: 'cheese', id: 'keju', emoji: '🧀' },
    { en: 'butter', id: 'mentega', emoji: '🧈' },
    { en: 'meat', id: 'daging', emoji: '🍖' },
    { en: 'soup', id: 'sup', emoji: '🍲' },
    { en: 'cake', id: 'kue', emoji: '🍰' },
    { en: 'cookie', id: 'biskuit', emoji: '🍪' },
    { en: 'chocolate', id: 'cokelat', emoji: '🍫' },
    { en: 'honey', id: 'madu', emoji: '🍯' },
    { en: 'salt', id: 'garam', emoji: '🧂' },
    { en: 'sugar', id: 'gula', emoji: '🍬' },
    { en: 'pizza', id: 'pizza', emoji: '🍕' },
    { en: 'burger', id: 'burger', emoji: '🍔' },
    { en: 'noodles', id: 'mie', emoji: '🍜' },
    { en: 'porridge', id: 'bubur', emoji: '🥣' },
    { en: 'sandwich', id: 'roti isi', emoji: '🥪' },
    { en: 'salad', id: 'salad', emoji: '🥗' },
    { en: 'juice', id: 'jus', emoji: '🧃' },
    { en: 'tea', id: 'teh', emoji: '🍵' },
    { en: 'coffee', id: 'kopi', emoji: '☕' },
    { en: 'soda', id: 'soda', emoji: '🥤' },
    { en: 'sea', id: 'laut', emoji: '🌊' },
    { en: 'volcano', id: 'gunung berapi', emoji: '🌋' },
    { en: 'desert', id: 'gurun', emoji: '🏜️' },
    { en: 'weather', id: 'cuaca', emoji: '🌦️' },
    { en: 'season', id: 'musim', emoji: '🍂' },
    { en: 'chef', id: 'koki', emoji: '🧑‍🍳' },
    { en: 'singer', id: 'penyanyi', emoji: '🧑‍🎤' },
    { en: 'artist', id: 'seniman', emoji: '🧑‍🎨' },
    { en: 'scientist', id: 'ilmuwan', emoji: '🧑‍🔬' },
    { en: 'pilot', id: 'pilot', emoji: '🧑‍✈️' },
    { en: 'astronaut', id: 'astronaut', emoji: '🧑‍🚀' },
    { en: 'firefighter', id: 'pemadam kebakaran', emoji: '🧑‍🚒' },
    { en: 'mechanic', id: 'montir', emoji: '🧑‍🔧' },
    { en: 'guard', id: 'penjaga', emoji: '💂' },
    { en: 'work', id: 'pekerjaan', emoji: '💼' },
    { en: 'dream', id: 'mimpi', emoji: '💭' },
    { en: 'idea', id: 'ide', emoji: '💡' },
    { en: 'plan', id: 'rencana', emoji: '🗒️' },
    { en: 'problem', id: 'masalah', emoji: '⚠️' },
    { en: 'help', id: 'bantuan', emoji: '🆘' },
    { en: 'time', id: 'waktu', emoji: '⏰' },
    { en: 'place', id: 'tempat', emoji: '📍' },
    { en: 'dictionary', id: 'kamus', emoji: '📖' },
  ],
  sentences: [
    { en: 'I have two cats', id: 'Saya punya dua kucing' },
    { en: 'We study English', id: 'Kami belajar bahasa Inggris' },
    { en: 'He buys a book', id: 'Dia membeli sebuah buku' },
    { en: 'They live in Jakarta', id: 'Mereka tinggal di Jakarta' },
    { en: 'I want to eat a mango', id: 'Saya ingin makan mangga' },
    { en: 'The cat sleeps on the sofa', id: 'Kucing itu tidur di sofa' },
    { en: 'Mother cooks rice', id: 'Ibu memasak nasi' },
    { en: 'The students read books', id: 'Murid-murid membaca buku' },
    { en: 'I go to the market with my mother', id: 'Saya pergi ke pasar bersama ibu' },
    { en: 'We buy vegetables at the market', id: 'Kami membeli sayur di pasar' },
    { en: 'The hospital is near the school', id: 'Rumah sakit itu dekat sekolah' },
    { en: 'The doctor works at the hospital', id: 'Dokter itu bekerja di rumah sakit' },
    { en: 'My uncle works at the bank', id: 'Paman saya bekerja di bank' },
    { en: 'We pray at the mosque', id: 'Kami beribadah di masjid' },
    { en: 'The library has many books', id: 'Perpustakaan itu punya banyak buku' },
    { en: 'I borrow a book from the library', id: 'Saya meminjam buku dari perpustakaan' },
    { en: 'We visit the museum on Sunday', id: 'Kami mengunjungi museum pada hari Minggu' },
    { en: 'The restaurant serves delicious food', id: 'Restoran itu menyajikan makanan lezat' },
    { en: 'We play football in the park', id: 'Kami bermain sepak bola di taman' },
    { en: 'The airport is very big', id: 'Bandara itu sangat besar' },
    { en: 'The train stops at the station', id: 'Kereta itu berhenti di stasiun' },
    { en: 'The ship is at the port', id: 'Kapal itu ada di pelabuhan' },
    { en: 'I send a letter at the post office', id: 'Saya mengirim surat di kantor pos' },
    { en: 'We see lions at the zoo', id: 'Kami melihat singa di kebun binatang' },
    { en: 'The farmer works on the farm', id: 'Petani itu bekerja di peternakan' },
    { en: 'The rice field is green', id: 'Sawahnya hijau' },
    { en: 'The forest is full of trees', id: 'Hutan itu penuh pohon' },
    { en: 'We swim at the beach', id: 'Kami berenang di pantai' },
    { en: 'The mountain is very high', id: 'Gunung itu sangat tinggi' },
    { en: 'The lake is calm', id: 'Danau itu tenang' },
    { en: 'The island is beautiful', id: 'Pulau itu indah' },
    { en: 'The garden has many flowers', id: 'Kebun itu punya banyak bunga' },
    { en: 'My mother cooks in the kitchen', id: 'Ibu saya memasak di dapur' },
    { en: 'I sleep in the bedroom', id: 'Saya tidur di kamar tidur' },
    { en: 'The bathroom is clean', id: 'Kamar mandinya bersih' },
    { en: 'We watch television in the living room', id: 'Kami menonton televisi di ruang tamu' },
    { en: 'We eat dinner in the dining room', id: 'Kami makan malam di ruang makan' },
    { en: 'The car is in the garage', id: 'Mobil itu ada di garasi' },
    { en: 'The roof is red', id: 'Atapnya merah' },
    { en: 'The wall is white', id: 'Dindingnya putih' },
    { en: 'I walk up the stairs', id: 'Saya berjalan menaiki tangga' },
    { en: 'The gate is open', id: 'Gerbangnya terbuka' },
    { en: 'The yard is big', id: 'Halamannya luas' },
    { en: 'I buy milk at the shop', id: 'Saya membeli susu di toko' },
    { en: 'The eggs are in the basket', id: 'Telur-telurnya ada di keranjang' },
    { en: 'I eat bread with butter', id: 'Saya makan roti dengan mentega' },
    { en: 'She drinks tea every morning', id: 'Dia minum teh setiap pagi' },
    { en: 'He drinks coffee at night', id: 'Dia minum kopi di malam hari' },
    { en: 'The soup is on the table', id: 'Supnya ada di meja' },
    { en: 'My mother bakes a cake', id: 'Ibu saya memanggang kue' },
    { en: 'We eat pizza on Friday', id: 'Kami makan pizza pada hari Jumat' },
    { en: 'He orders a burger', id: 'Dia memesan burger' },
    { en: 'I cook noodles for lunch', id: 'Saya memasak mie untuk makan siang' },
    { en: 'She eats porridge for breakfast', id: 'Dia makan bubur untuk sarapan' },
    { en: 'He makes a sandwich', id: 'Dia membuat roti isi' },
    { en: 'We eat salad with vegetables', id: 'Kami makan salad dengan sayur' },
    { en: 'I drink orange juice', id: 'Saya minum jus jeruk' },
    { en: 'The chef cooks in the restaurant', id: 'Koki itu memasak di restoran' },
    { en: 'The singer sings a beautiful song', id: 'Penyanyi itu menyanyikan lagu yang indah' },
    { en: 'The artist paints a picture', id: 'Seniman itu melukis gambar' },
    { en: 'The scientist works in a laboratory', id: 'Ilmuwan itu bekerja di laboratorium' },
    { en: 'The pilot flies an airplane', id: 'Pilot itu menerbangkan pesawat' },
    { en: 'The astronaut goes to space', id: 'Astronaut itu pergi ke luar angkasa' },
    { en: 'The firefighter is very brave', id: 'Pemadam kebakaran itu sangat berani' },
    { en: 'The mechanic fixes the car', id: 'Montir itu memperbaiki mobil' },
    { en: 'The guard watches the gate', id: 'Penjaga itu menjaga gerbang' },
    { en: 'My father works in an office', id: 'Ayah saya bekerja di kantor' },
    { en: 'My mother is a teacher', id: 'Ibu saya seorang guru' },
    { en: 'The students study in the classroom', id: 'Murid-murid belajar di kelas' },
    { en: 'The teacher writes on the board', id: 'Guru itu menulis di papan tulis' },
    { en: 'I keep my money in the wallet', id: 'Saya menyimpan uang di dompet' },
    { en: 'She puts the key in her bag', id: 'Dia menaruh kunci di tasnya' },
    { en: "The clock shows seven o'clock", id: 'Jam itu menunjukkan pukul tujuh' },
    { en: 'I look at the mirror', id: 'Saya melihat ke cermin' },
    { en: 'The window is open', id: 'Jendelanya terbuka' },
    { en: 'The door is closed', id: 'Pintunya tertutup' },
    { en: 'I turn off the lamp', id: 'Saya mematikan lampu' },
    { en: 'The blanket is soft', id: 'Selimutnya lembut' },
    { en: 'The pillow is on the bed', id: 'Bantalnya ada di tempat tidur' },
    { en: 'The carpet is blue', id: 'Karpetnya biru' },
    { en: 'The sofa is comfortable', id: 'Sofanya nyaman' },
    { en: 'The spoon and fork are clean', id: 'Sendok dan garpunya bersih' },
    { en: 'The plate is on the table', id: 'Piringnya ada di meja' },
    { en: 'The knife cuts the bread', id: 'Pisau itu memotong roti' },
    { en: 'The cup is full of tea', id: 'Cangkirnya penuh teh' },
    { en: 'The bottle is empty', id: 'Botolnya kosong' },
    { en: 'The pan is hot', id: 'Penggorengannya panas' },
    { en: 'The kettle is on the stove', id: 'Ketelnya ada di atas kompor' },
    { en: 'The refrigerator keeps food cold', id: 'Kulkas menjaga makanan tetap dingin' },
    { en: 'The radio plays music', id: 'Radio itu memutar musik' },
    { en: 'The telephone is ringing', id: 'Teleponnya berdering' },
    { en: 'The computer is new', id: 'Komputernya baru' },
    { en: 'The basket is full of fruit', id: 'Keranjangnya penuh buah' },
    { en: 'The box is heavy', id: 'Kotaknya berat' },
    { en: 'The ball rolls on the floor', id: 'Bola itu menggelinding di lantai' },
    { en: 'The kite flies in the sky', id: 'Layangannya terbang di langit' },
    { en: 'The balloon is red', id: 'Balonnya merah' },
    { en: 'My brother plays the drum', id: 'Kakak saya bermain drum' },
    { en: 'My sister plays the piano', id: 'Kakak saya bermain piano' },
    { en: 'We sing together at the party', id: 'Kami bernyanyi bersama di pesta' },
    { en: 'The gift is in the box', id: 'Hadiahnya ada di dalam kotak' },
    { en: 'She writes a letter to her friend', id: 'Dia menulis surat untuk temannya' },
    { en: 'The picture hangs on the wall', id: 'Gambar itu tergantung di dinding' },
    { en: 'I learn numbers at school', id: 'Saya belajar angka di sekolah' },
    { en: 'The question is easy', id: 'Pertanyaannya mudah' },
    { en: 'The answer is correct', id: 'Jawabannya benar' },
    { en: 'He wins a prize', id: 'Dia memenangkan hadiah' },
    { en: 'The class starts at seven', id: 'Kelasnya mulai pukul tujuh' },
    { en: 'We have a test today', id: 'Kami ada ujian hari ini' },
    { en: 'The lesson is interesting', id: 'Pelajaran itu menarik' },
    { en: 'We go on holiday to the beach', id: 'Kami pergi berlibur ke pantai' },
    { en: 'My birthday is in May', id: 'Ulang tahun saya di bulan Mei' },
    { en: 'I am sick today', id: 'Saya sakit hari ini' },
    { en: 'She takes medicine', id: 'Dia minum obat' },
    { en: 'He stays healthy', id: 'Dia tetap sehat' },
    { en: 'I sweep the floor with a broom', id: 'Saya menyapu lantai dengan sapu' },
    { en: 'We throw trash in the bin', id: 'Kami membuang sampah di tempat sampah' },
    { en: 'The room is messy', id: 'Kamarnya berantakan' },
    { en: 'I clean my room every day', id: 'Saya membersihkan kamar setiap hari' },
    { en: 'The story is very good', id: 'Ceritanya sangat bagus' },
    { en: 'The song is popular', id: 'Lagunya populer' },
    { en: 'The game is fun', id: 'Permainannya seru' },
    { en: 'I fly a kite in the field', id: 'Saya menerbangkan layangan di sawah' },
    { en: 'We ride bicycles in the park', id: 'Kami bersepeda di taman' },
    { en: 'The bus stops near my house', id: 'Bus itu berhenti dekat rumah saya' },
    { en: 'The boat sails on the sea', id: 'Perahu itu berlayar di laut' },
    { en: 'The motorcycle is fast', id: 'Sepeda motor itu cepat' },
    { en: 'The taxi waits on the street', id: 'Taksi itu menunggu di jalan' },
    { en: 'The helicopter flies over the city', id: 'Helikopter itu terbang di atas kota' },
    { en: 'The truck carries heavy things', id: 'Truk itu membawa barang berat' },
    { en: 'I see a rocket in the sky', id: 'Saya melihat roket di langit' },
    { en: 'The moon shines at night', id: 'Bulan bersinar di malam hari' },
    { en: 'The stars are bright', id: 'Bintang-bintangnya terang' },
    { en: 'The sun rises in the morning', id: 'Matahari terbit di pagi hari' },
    { en: 'The rain falls on the roof', id: 'Hujan turun di atas atap' },
    { en: 'The wind blows softly', id: 'Angin bertiup lembut' },
    { en: 'The snow is white', id: 'Saljunya putih' },
    { en: 'The rainbow has many colors', id: 'Pelangi punya banyak warna' },
    { en: 'The volcano is dangerous', id: 'Gunung berapi itu berbahaya' },
    { en: 'The desert is very hot', id: 'Gurunnya sangat panas' },
    { en: 'The sea is blue', id: 'Lautnya biru' },
    { en: 'The wave is big', id: 'Ombaknya besar' },
    { en: 'The weather is cloudy today', id: 'Cuacanya berawan hari ini' },
    { en: 'We wear jackets in the rainy season', id: 'Kami memakai jaket di musim hujan' },
    { en: 'She wears a scarf in winter', id: 'Dia memakai syal di musim dingin' },
    { en: 'He wears gloves when it is cold', id: 'Dia memakai sarung tangan saat dingin' },
    { en: 'My shoes are wet', id: 'Sepatu saya basah' },
    { en: 'The boots are heavy', id: 'Sepatu botnya berat' },
    { en: 'I pack my clothes in the suitcase', id: 'Saya mengemas pakaian di koper' },
    { en: 'The lamp lights the room', id: 'Lampu itu menerangi ruangan' },
    { en: 'The candle is bright', id: 'Lilinnya terang' },
    { en: 'I draw a map of my city', id: 'Saya menggambar peta kota saya' },
    { en: 'The flag waves in the wind', id: 'Bendera berkibar di angin' },
    { en: 'The world is very big', id: 'Dunia itu sangat luas' },
    { en: 'Indonesia is a beautiful country', id: 'Indonesia negara yang indah' },
    { en: 'We love our country', id: 'Kami mencintai negara kami' },
    { en: 'I save money in the bank', id: 'Saya menabung uang di bank' },
    { en: 'Water flows from the mountain to the sea', id: 'Air mengalir dari gunung ke laut' },
    { en: 'The bridge is over the river', id: 'Jembatan itu di atas sungai' },
    { en: 'The sea is deep', id: 'Lautnya dalam' },
  ],
};
