import type { EnglishLevel } from './types';

export const LEVEL_2: EnglishLevel = {
  id: 2,
  name: 'Frasa Harian',
  desc: 'Keluarga, aktivitas, sifat, dan waktu',
  vocab: [
    { en: 'mother', id: 'ibu', emoji: '👩' },
    { en: 'father', id: 'ayah', emoji: '👨' },
    { en: 'sister', id: 'kakak perempuan', emoji: '👧' },
    { en: 'brother', id: 'kakak laki-laki', emoji: '👦' },
    { en: 'grandmother', id: 'nenek', emoji: '👵' },
    { en: 'grandfather', id: 'kakek', emoji: '👴' },
    { en: 'aunt', id: 'bibi', emoji: '👩' },
    { en: 'uncle', id: 'paman', emoji: '👨' },
    { en: 'cousin', id: 'sepupu', emoji: '🧑' },
    { en: 'parents', id: 'orang tua', emoji: '👫' },
    { en: 'eat', id: 'makan', emoji: '🍽️' },
    { en: 'drink', id: 'minum', emoji: '🥤' },
    { en: 'sleep', id: 'tidur', emoji: '😴' },
    { en: 'run', id: 'berlari', emoji: '🏃' },
    { en: 'read', id: 'membaca', emoji: '📖' },
    { en: 'write', id: 'menulis', emoji: '✍️' },
    { en: 'play', id: 'bermain', emoji: '⚽' },
    { en: 'study', id: 'belajar', emoji: '📚' },
    { en: 'walk', id: 'berjalan', emoji: '🚶' },
    { en: 'jump', id: 'melompat', emoji: '🤸' },
    { en: 'swim', id: 'berenang', emoji: '🏊' },
    { en: 'sing', id: 'bernyanyi', emoji: '🎤' },
    { en: 'dance', id: 'menari', emoji: '💃' },
    { en: 'cook', id: 'memasak', emoji: '🍳' },
    { en: 'wash', id: 'mencuci', emoji: '🧼' },
    { en: 'clean', id: 'membersihkan', emoji: '🧹' },
    { en: 'cry', id: 'menangis', emoji: '😭' },
    { en: 'laugh', id: 'tertawa', emoji: '😂' },
    { en: 'smile', id: 'tersenyum', emoji: '🙂' },
    { en: 'speak', id: 'berbicara', emoji: '🗣️' },
    { en: 'look', id: 'melihat', emoji: '👀' },
    { en: 'buy', id: 'membeli', emoji: '🛒' },
    { en: 'wait', id: 'menunggu', emoji: '⏳' },
    { en: 'climb', id: 'memanjat', emoji: '🧗' },
    { en: 'ride', id: 'mengendarai', emoji: '🚴' },
    { en: 'fly', id: 'terbang', emoji: '🕊️' },
    { en: 'draw', id: 'menggambar', emoji: '🎨' },
    { en: 'throw', id: 'melempar', emoji: '🏀' },
    { en: 'catch', id: 'menangkap', emoji: '🧤' },
    { en: 'push', id: 'mendorong', emoji: '👊' },
    { en: 'pull', id: 'menarik', emoji: '✊' },
    { en: 'hold', id: 'memegang', emoji: '🤲' },
    { en: 'carry', id: 'membawa', emoji: '📦' },
    { en: 'cut', id: 'memotong', emoji: '✂️' },
    { en: 'mix', id: 'mencampur', emoji: '🥣' },
    { en: 'share', id: 'berbagi', emoji: '🤝' },
    { en: 'send', id: 'mengirim', emoji: '📨' },
    { en: 'find', id: 'menemukan', emoji: '🔍' },
    { en: 'win', id: 'menang', emoji: '🏅' },
    { en: 'listen', id: 'mendengarkan', emoji: '🎧' },
    { en: 'touch', id: 'menyentuh', emoji: '👆' },
    { en: 'build', id: 'membangun', emoji: '🧱' },
    { en: 'fix', id: 'memperbaiki', emoji: '🔧' },
    { en: 'plant', id: 'menanam', emoji: '🌱' },
    { en: 'count', id: 'menghitung', emoji: '🔢' },
    { en: 'ask', id: 'bertanya', emoji: '🙋' },
    { en: 'start', id: 'memulai', emoji: '▶️' },
    { en: 'stop', id: 'berhenti', emoji: '🛑' },
    { en: 'drive', id: 'mengemudi', emoji: '🚗' },
    { en: 'big', id: 'besar', emoji: '🐘' },
    { en: 'small', id: 'kecil', emoji: '🐜' },
    { en: 'fast', id: 'cepat', emoji: '🐆' },
    { en: 'slow', id: 'lambat', emoji: '🐢' },
    { en: 'happy', id: 'senang', emoji: '😊' },
    { en: 'sad', id: 'sedih', emoji: '😢' },
    { en: 'hot', id: 'panas', emoji: '🔥' },
    { en: 'cold', id: 'dingin', emoji: '❄️' },
    { en: 'new', id: 'baru', emoji: '✨' },
    { en: 'old', id: 'tua', emoji: '👴' },
    { en: 'young', id: 'muda', emoji: '🧒' },
    { en: 'tall', id: 'tinggi', emoji: '📏' },
    { en: 'short', id: 'pendek', emoji: '📐' },
    { en: 'long', id: 'panjang', emoji: '🧵' },
    { en: 'strong', id: 'kuat', emoji: '💪' },
    { en: 'beautiful', id: 'cantik', emoji: '🌺' },
    { en: 'smart', id: 'pintar', emoji: '🧠' },
    { en: 'funny', id: 'lucu', emoji: '😄' },
    { en: 'kind', id: 'baik', emoji: '💖' },
    { en: 'tired', id: 'lelah', emoji: '😴' },
    { en: 'hungry', id: 'lapar', emoji: '😋' },
    { en: 'thirsty', id: 'haus', emoji: '🥤' },
    { en: 'noisy', id: 'berisik', emoji: '📢' },
    { en: 'quiet', id: 'tenang', emoji: '🤫' },
    { en: 'bright', id: 'terang', emoji: '🔆' },
    { en: 'dark', id: 'gelap', emoji: '🌑' },
    { en: 'heavy', id: 'berat', emoji: '⚖️' },
    { en: 'soft', id: 'lembut', emoji: '🧸' },
    { en: 'dirty', id: 'kotor', emoji: '🧹' },
    { en: 'full', id: 'penuh', emoji: '🈵' },
    { en: 'empty', id: 'kosong', emoji: '🫙' },
    { en: 'open', id: 'terbuka', emoji: '🔓' },
    { en: 'closed', id: 'tertutup', emoji: '🔒' },
    { en: 'wet', id: 'basah', emoji: '💦' },
    { en: 'dry', id: 'kering', emoji: '🌵' },
    { en: 'sharp', id: 'tajam', emoji: '🔪' },
    { en: 'sweet', id: 'manis', emoji: '🍬' },
    { en: 'salty', id: 'asin', emoji: '🧂' },
    { en: 'sour', id: 'asam', emoji: '🍋' },
    { en: 'spicy', id: 'pedas', emoji: '🌶️' },
    { en: 'delicious', id: 'lezat', emoji: '😋' },
    { en: 'safe', id: 'aman', emoji: '🛡️' },
    { en: 'polite', id: 'sopan', emoji: '🙏' },
    { en: 'morning', id: 'pagi', emoji: '🌅' },
    { en: 'night', id: 'malam', emoji: '🌙' },
    { en: 'day', id: 'hari', emoji: '☀️' },
    { en: 'week', id: 'minggu', emoji: '📅' },
    { en: 'month', id: 'bulan', emoji: '📆' },
    { en: 'year', id: 'tahun', emoji: '🗓️' },
    { en: 'evening', id: 'sore', emoji: '🌆' },
    { en: 'afternoon', id: 'siang', emoji: '🌇' },
    { en: 'noon', id: 'tengah hari', emoji: '🕛' },
    { en: 'hour', id: 'jam', emoji: '🕐' },
    { en: 'minute', id: 'menit', emoji: '⏱️' },
    { en: 'today', id: 'hari ini', emoji: '📅' },
    { en: 'sunny', id: 'cerah', emoji: '☀️' },
    { en: 'cloudy', id: 'berawan', emoji: '☁️' },
    { en: 'windy', id: 'berangin', emoji: '🌬️' },
    { en: 'snowy', id: 'bersalju', emoji: '❄️' },
    { en: 'stormy', id: 'badai', emoji: '⛈️' },
    { en: 'breakfast', id: 'sarapan', emoji: '🥞' },
    { en: 'lunch', id: 'makan siang', emoji: '🍱' },
    { en: 'dinner', id: 'makan malam', emoji: '🍛' },
    { en: 'snack', id: 'camilan', emoji: '🍿' },
    { en: 'angry', id: 'marah', emoji: '😠' },
    { en: 'scared', id: 'takut', emoji: '😨' },
    { en: 'surprised', id: 'terkejut', emoji: '😲' },
    { en: 'bored', id: 'bosan', emoji: '😑' },
    { en: 'excited', id: 'bersemangat', emoji: '🤩' },
    { en: 'proud', id: 'bangga', emoji: '😌' },
    { en: 'shy', id: 'malu', emoji: '😳' },
    { en: 'phone', id: 'ponsel', emoji: '📱' },
    { en: 'soap', id: 'sabun', emoji: '🧼' },
    { en: 'toothbrush', id: 'sikat gigi', emoji: '🪥' },
    { en: 'wallet', id: 'dompet', emoji: '💳' },
    { en: 'purse', id: 'tas kecil', emoji: '👛' },
    { en: 'story', id: 'cerita', emoji: '📖' },
    { en: 'song', id: 'lagu', emoji: '🎵' },
    { en: 'game', id: 'permainan', emoji: '🎮' },
    { en: 'gift', id: 'hadiah', emoji: '🎁' },
    { en: 'letter', id: 'surat', emoji: '✉️' },
    { en: 'picture', id: 'gambar', emoji: '🖼️' },
    { en: 'color', id: 'warna', emoji: '🎨' },
    { en: 'number', id: 'angka', emoji: '🔢' },
    { en: 'question', id: 'pertanyaan', emoji: '❓' },
    { en: 'answer', id: 'jawaban', emoji: '✅' },
    { en: 'prize', id: 'piala', emoji: '🏆' },
    { en: 'party', id: 'pesta', emoji: '🎉' },
    { en: 'music', id: 'musik', emoji: '🎶' },
    { en: 'movie', id: 'film', emoji: '🎬' },
    { en: 'homework', id: 'pekerjaan rumah', emoji: '📝' },
    { en: 'test', id: 'ujian', emoji: '📄' },
    { en: 'class', id: 'kelas', emoji: '🏫' },
    { en: 'lesson', id: 'pelajaran', emoji: '📚' },
    { en: 'holiday', id: 'liburan', emoji: '🏖️' },
    { en: 'birthday', id: 'ulang tahun', emoji: '🎂' },
    { en: 'sick', id: 'sakit', emoji: '🤒' },
    { en: 'healthy', id: 'sehat', emoji: '💪' },
    { en: 'medicine', id: 'obat', emoji: '💊' },
    { en: 'broom', id: 'sapu', emoji: '🧹' },
    { en: 'trash', id: 'sampah', emoji: '🗑️' },
  ],
  sentences: [
    { en: 'She eats rice', id: 'Dia makan nasi' },
    { en: 'We go to school', id: 'Kami pergi ke sekolah' },
    { en: 'Father reads a book', id: 'Ayah membaca buku' },
    { en: 'Mother drinks tea', id: 'Ibu minum teh' },
    { en: 'They play ball', id: 'Mereka bermain bola' },
    { en: 'You are my friend', id: 'Kamu adalah temanku' },
    { en: 'My brother runs fast', id: 'Kakakku berlari cepat' },
    { en: 'I sleep at night', id: 'Saya tidur di malam hari' },
    { en: 'I wake up early', id: 'Saya bangun pagi' },
    { en: 'I brush my teeth', id: 'Saya menyikat gigi' },
    { en: 'I take a bath', id: 'Saya mandi' },
    { en: 'We eat breakfast together', id: 'Kami sarapan bersama' },
    { en: 'She wears a red shirt', id: 'Dia memakai kemeja merah' },
    { en: 'He helps his mother', id: 'Dia membantu ibunya' },
    { en: 'They clean the house', id: 'Mereka membersihkan rumah' },
    { en: 'My father drives a car', id: 'Ayah saya mengendarai mobil' },
    { en: 'My mother cooks dinner', id: 'Ibu saya memasak makan malam' },
    { en: 'I do my homework', id: 'Saya mengerjakan pekerjaan rumah' },
    { en: 'We watch a movie', id: 'Kami menonton film' },
    { en: 'She listens to music', id: 'Dia mendengarkan musik' },
    { en: 'He plays the guitar', id: 'Dia bermain gitar' },
    { en: 'I feed my cat', id: 'Saya memberi makan kucing saya' },
    { en: 'We walk to the park', id: 'Kami berjalan ke taman' },
    { en: 'You are very kind', id: 'Kamu sangat baik' },
    { en: 'I am hungry now', id: 'Saya lapar sekarang' },
    { en: 'She is tired today', id: 'Dia lelah hari ini' },
    { en: 'He is my best friend', id: 'Dia sahabat saya' },
    { en: 'We are a happy family', id: 'Kami keluarga yang bahagia' },
    { en: 'The weather is sunny', id: 'Cuacanya cerah' },
    { en: 'It is raining today', id: 'Hari ini hujan' },
    { en: 'I wear a jacket', id: 'Saya memakai jaket' },
    { en: 'She wears warm socks', id: 'Dia memakai kaus kaki hangat' },
    { en: 'He washes his hands', id: 'Dia mencuci tangannya' },
    { en: 'We share our snacks', id: 'Kami berbagi camilan' },
    { en: 'They play in the yard', id: 'Mereka bermain di halaman' },
    { en: 'I read a story', id: 'Saya membaca cerita' },
    { en: 'She draws a picture', id: 'Dia menggambar gambar' },
    { en: 'He counts to ten', id: 'Dia berhitung sampai sepuluh' },
    { en: 'We sing a happy song', id: 'Kami menyanyikan lagu gembira' },
    { en: 'I open the window', id: 'Saya membuka jendela' },
    { en: 'She closes the door', id: 'Dia menutup pintu' },
    { en: 'He turns on the lamp', id: 'Dia menyalakan lampu' },
    { en: 'I sit on the chair', id: 'Saya duduk di kursi' },
    { en: 'The food is delicious', id: 'Makanannya lezat' },
    { en: 'The soup is hot', id: 'Supnya panas' },
    { en: 'The ice cream is sweet', id: 'Es krimnya manis' },
    { en: 'I like my new shoes', id: 'Saya suka sepatu baru saya' },
    { en: 'My bag is heavy', id: 'Tasku berat' },
    { en: 'The box is empty', id: 'Kotaknya kosong' },
    { en: 'The glass is full', id: 'Gelasnya penuh' },
    { en: 'The floor is clean', id: 'Lantainya bersih' },
    { en: 'My hands are wet', id: 'Tanganku basah' },
    { en: 'The towel is dry', id: 'Handuknya kering' },
    { en: 'The knife is sharp', id: 'Pisau itu tajam' },
    { en: 'The baby is sleeping', id: 'Bayi itu sedang tidur' },
    { en: 'The dog is running', id: 'Anjing itu sedang berlari' },
    { en: 'The bird is singing', id: 'Burung itu sedang bernyanyi' },
    { en: 'The children are playing', id: 'Anak-anak sedang bermain' },
    { en: 'Mother is cooking', id: 'Ibu sedang memasak' },
    { en: 'Father is reading', id: 'Ayah sedang membaca' },
    { en: 'I am drawing a cat', id: 'Saya sedang menggambar kucing' },
    { en: 'We are studying English', id: 'Kami sedang belajar bahasa Inggris' },
    { en: 'She is writing a letter', id: 'Dia sedang menulis surat' },
    { en: 'He is riding a bicycle', id: 'Dia sedang mengendarai sepeda' },
    { en: 'They are swimming', id: 'Mereka sedang berenang' },
    { en: 'I can jump high', id: 'Saya bisa melompat tinggi' },
    { en: 'She can dance well', id: 'Dia bisa menari dengan baik' },
    { en: 'He can climb a tree', id: 'Dia bisa memanjat pohon' },
    { en: 'We can sing together', id: 'Kami bisa bernyanyi bersama' },
    { en: 'I want to sleep', id: 'Saya ingin tidur' },
    { en: 'She wants to drink juice', id: 'Dia ingin minum jus' },
    { en: 'He wants a new toy', id: 'Dia ingin mainan baru' },
    { en: 'We need more water', id: 'Kami butuh lebih banyak air' },
    { en: 'I love my parents', id: 'Saya sayang orang tua saya' },
    { en: 'She loves her grandmother', id: 'Dia sayang neneknya' },
    { en: 'He misses his uncle', id: 'Dia merindukan pamannya' },
    { en: 'My cousin is funny', id: 'Sepupu saya lucu' },
    { en: 'The baby is crying', id: 'Bayi itu menangis' },
    { en: 'My sister is smiling', id: 'Kakak perempuan saya tersenyum' },
    { en: 'The clown is funny', id: 'Badut itu lucu' },
    { en: 'I am scared of spiders', id: 'Saya takut laba-laba' },
    { en: 'She is proud of me', id: 'Dia bangga pada saya' },
    { en: 'He is surprised', id: 'Dia terkejut' },
    { en: 'I am bored at home', id: 'Saya bosan di rumah' },
    { en: 'We are excited today', id: 'Kami bersemangat hari ini' },
    { en: 'Do not be lazy', id: 'Jangan malas' },
    { en: 'Please be careful', id: 'Tolong hati-hati' },
    { en: 'The street is noisy', id: 'Jalannya berisik' },
    { en: 'The room is quiet', id: 'Kamarnya tenang' },
    { en: 'The night is dark', id: 'Malam itu gelap' },
  ],
};
