import type { EnglishLevel } from './types';

export const LEVEL_1: EnglishLevel = {
  id: 1,
  name: 'Kata Dasar',
  desc: 'Hewan, buah, warna, dan benda sehari-hari',
  vocab: [
    { en: 'cat', id: 'kucing', emoji: '🐱' },
    { en: 'dog', id: 'anjing', emoji: '🐶' },
    { en: 'bird', id: 'burung', emoji: '🐦' },
    { en: 'fish', id: 'ikan', emoji: '🐟' },
    { en: 'cow', id: 'sapi', emoji: '🐮' },
    { en: 'rabbit', id: 'kelinci', emoji: '🐰' },
    { en: 'duck', id: 'bebek', emoji: '🦆' },
    { en: 'chicken', id: 'ayam', emoji: '🐔' },
    { en: 'rooster', id: 'ayam jago', emoji: '🐓' },
    { en: 'goat', id: 'kambing', emoji: '🐐' },
    { en: 'sheep', id: 'domba', emoji: '🐑' },
    { en: 'horse', id: 'kuda', emoji: '🐴' },
    { en: 'elephant', id: 'gajah', emoji: '🐘' },
    { en: 'lion', id: 'singa', emoji: '🦁' },
    { en: 'tiger', id: 'harimau', emoji: '🐯' },
    { en: 'monkey', id: 'monyet', emoji: '🐵' },
    { en: 'bear', id: 'beruang', emoji: '🐻' },
    { en: 'pig', id: 'babi', emoji: '🐷' },
    { en: 'frog', id: 'katak', emoji: '🐸' },
    { en: 'snake', id: 'ular', emoji: '🐍' },
    { en: 'turtle', id: 'kura-kura', emoji: '🐢' },
    { en: 'mouse', id: 'tikus', emoji: '🐭' },
    { en: 'butterfly', id: 'kupu-kupu', emoji: '🦋' },
    { en: 'bee', id: 'lebah', emoji: '🐝' },
    { en: 'ant', id: 'semut', emoji: '🐜' },
    { en: 'spider', id: 'laba-laba', emoji: '🕷️' },
    { en: 'giraffe', id: 'jerapah', emoji: '🦒' },
    { en: 'zebra', id: 'zebra', emoji: '🦓' },
    { en: 'penguin', id: 'penguin', emoji: '🐧' },
    { en: 'dolphin', id: 'lumba-lumba', emoji: '🐬' },
    { en: 'whale', id: 'paus', emoji: '🐳' },
    { en: 'shark', id: 'hiu', emoji: '🦈' },
    { en: 'owl', id: 'burung hantu', emoji: '🦉' },
    { en: 'eagle', id: 'elang', emoji: '🦅' },
    { en: 'kangaroo', id: 'kangguru', emoji: '🦘' },
    { en: 'panda', id: 'panda', emoji: '🐼' },
    { en: 'camel', id: 'unta', emoji: '🐪' },
    { en: 'deer', id: 'rusa', emoji: '🦌' },
    { en: 'fox', id: 'rubah', emoji: '🦊' },
    { en: 'wolf', id: 'serigala', emoji: '🐺' },
    { en: 'squirrel', id: 'tupai', emoji: '🐿️' },
    { en: 'crab', id: 'kepiting', emoji: '🦀' },
    { en: 'octopus', id: 'gurita', emoji: '🐙' },
    { en: 'snail', id: 'siput', emoji: '🐌' },
    { en: 'apple', id: 'apel', emoji: '🍎' },
    { en: 'banana', id: 'pisang', emoji: '🍌' },
    { en: 'orange', id: 'jeruk', emoji: '🍊' },
    { en: 'mango', id: 'mangga', emoji: '🥭' },
    { en: 'grape', id: 'anggur', emoji: '🍇' },
    { en: 'watermelon', id: 'semangka', emoji: '🍉' },
    { en: 'strawberry', id: 'stroberi', emoji: '🍓' },
    { en: 'pineapple', id: 'nanas', emoji: '🍍' },
    { en: 'melon', id: 'melon', emoji: '🍈' },
    { en: 'lemon', id: 'lemon', emoji: '🍋' },
    { en: 'peach', id: 'persik', emoji: '🍑' },
    { en: 'cherry', id: 'ceri', emoji: '🍒' },
    { en: 'blueberry', id: 'beri biru', emoji: '🫐' },
    { en: 'kiwi', id: 'kiwi', emoji: '🥝' },
    { en: 'pear', id: 'pir', emoji: '🍐' },
    { en: 'coconut', id: 'kelapa', emoji: '🥥' },
    { en: 'avocado', id: 'alpukat', emoji: '🥑' },
    { en: 'carrot', id: 'wortel', emoji: '🥕' },
    { en: 'potato', id: 'kentang', emoji: '🥔' },
    { en: 'tomato', id: 'tomat', emoji: '🍅' },
    { en: 'onion', id: 'bawang bombai', emoji: '🧅' },
    { en: 'garlic', id: 'bawang putih', emoji: '🧄' },
    { en: 'corn', id: 'jagung', emoji: '🌽' },
    { en: 'cucumber', id: 'mentimun', emoji: '🥒' },
    { en: 'spinach', id: 'bayam', emoji: '🥬' },
    { en: 'broccoli', id: 'brokoli', emoji: '🥦' },
    { en: 'pumpkin', id: 'labu', emoji: '🎃' },
    { en: 'chili', id: 'cabai', emoji: '🌶️' },
    { en: 'mushroom', id: 'jamur', emoji: '🍄' },
    { en: 'eggplant', id: 'terong', emoji: '🍆' },
    { en: 'pea', id: 'kacang polong', emoji: '🫛' },
    { en: 'cabbage', id: 'kol', emoji: '🥬' },
    { en: 'red', id: 'merah', emoji: '🔴' },
    { en: 'blue', id: 'biru', emoji: '🔵' },
    { en: 'yellow', id: 'kuning', emoji: '🟡' },
    { en: 'green', id: 'hijau', emoji: '🟢' },
    { en: 'black', id: 'hitam', emoji: '⚫' },
    { en: 'white', id: 'putih', emoji: '⚪' },
    { en: 'pink', id: 'merah muda', emoji: '🩷' },
    { en: 'purple', id: 'ungu', emoji: '🟣' },
    { en: 'brown', id: 'cokelat', emoji: '🟤' },
    { en: 'one', id: 'satu', emoji: '1️⃣' },
    { en: 'two', id: 'dua', emoji: '2️⃣' },
    { en: 'three', id: 'tiga', emoji: '3️⃣' },
    { en: 'four', id: 'empat', emoji: '4️⃣' },
    { en: 'five', id: 'lima', emoji: '5️⃣' },
    { en: 'six', id: 'enam', emoji: '6️⃣' },
    { en: 'seven', id: 'tujuh', emoji: '7️⃣' },
    { en: 'eight', id: 'delapan', emoji: '8️⃣' },
    { en: 'nine', id: 'sembilan', emoji: '9️⃣' },
    { en: 'ten', id: 'sepuluh', emoji: '🔟' },
    { en: 'head', id: 'kepala', emoji: '👤' },
    { en: 'hair', id: 'rambut', emoji: '💇' },
    { en: 'eye', id: 'mata', emoji: '👁️' },
    { en: 'ear', id: 'telinga', emoji: '👂' },
    { en: 'nose', id: 'hidung', emoji: '👃' },
    { en: 'mouth', id: 'mulut', emoji: '👄' },
    { en: 'tooth', id: 'gigi', emoji: '🦷' },
    { en: 'tongue', id: 'lidah', emoji: '👅' },
    { en: 'hand', id: 'tangan', emoji: '✋' },
    { en: 'arm', id: 'lengan', emoji: '💪' },
    { en: 'finger', id: 'jari', emoji: '☝️' },
    { en: 'leg', id: 'kaki', emoji: '🦵' },
    { en: 'foot', id: 'telapak kaki', emoji: '🦶' },
    { en: 'knee', id: 'lutut', emoji: '🦵' },
    { en: 'heart', id: 'jantung', emoji: '❤️' },
    { en: 'brain', id: 'otak', emoji: '🧠' },
    { en: 'bone', id: 'tulang', emoji: '🦴' },
    { en: 'face', id: 'wajah', emoji: '😊' },
    { en: 'book', id: 'buku', emoji: '📖' },
    { en: 'pencil', id: 'pensil', emoji: '✏️' },
    { en: 'bag', id: 'tas', emoji: '🎒' },
    { en: 'chair', id: 'kursi', emoji: '🪑' },
    { en: 'table', id: 'meja', emoji: '🍽️' },
    { en: 'bed', id: 'tempat tidur', emoji: '🛏️' },
    { en: 'lamp', id: 'lampu', emoji: '💡' },
    { en: 'sofa', id: 'sofa', emoji: '🛋️' },
    { en: 'carpet', id: 'karpet', emoji: '🧶' },
    { en: 'pillow', id: 'bantal', emoji: '🛏️' },
    { en: 'blanket', id: 'selimut', emoji: '🛌' },
    { en: 'plate', id: 'piring', emoji: '🍽️' },
    { en: 'spoon', id: 'sendok', emoji: '🥄' },
    { en: 'fork', id: 'garpu', emoji: '🍴' },
    { en: 'knife', id: 'pisau', emoji: '🔪' },
    { en: 'cup', id: 'cangkir', emoji: '☕' },
    { en: 'bottle', id: 'botol', emoji: '🍼' },
    { en: 'pan', id: 'penggorengan', emoji: '🍳' },
    { en: 'kettle', id: 'ketel', emoji: '🫖' },
    { en: 'refrigerator', id: 'kulkas', emoji: '🧊' },
    { en: 'television', id: 'televisi', emoji: '📺' },
    { en: 'radio', id: 'radio', emoji: '📻' },
    { en: 'telephone', id: 'telepon', emoji: '☎️' },
    { en: 'computer', id: 'komputer', emoji: '💻' },
    { en: 'basket', id: 'keranjang', emoji: '🧺' },
    { en: 'box', id: 'kotak', emoji: '📦' },
    { en: 'ball', id: 'bola', emoji: '⚽' },
    { en: 'toy', id: 'mainan', emoji: '🧸' },
    { en: 'kite', id: 'layangan', emoji: '🪁' },
    { en: 'balloon', id: 'balon', emoji: '🎈' },
    { en: 'drum', id: 'drum', emoji: '🥁' },
    { en: 'guitar', id: 'gitar', emoji: '🎸' },
    { en: 'piano', id: 'piano', emoji: '🎹' },
    { en: 'pen', id: 'pulpen', emoji: '🖊️' },
    { en: 'eraser', id: 'penghapus', emoji: '🧽' },
    { en: 'ruler', id: 'penggaris', emoji: '📏' },
    { en: 'crayon', id: 'krayon', emoji: '🖍️' },
    { en: 'notebook', id: 'buku tulis', emoji: '📓' },
    { en: 'scissors', id: 'gunting', emoji: '✂️' },
    { en: 'glue', id: 'lem', emoji: '🧴' },
    { en: 'paper', id: 'kertas', emoji: '📄' },
    { en: 'candy', id: 'permen', emoji: '🍬' },
    { en: 'ice cream', id: 'es krim', emoji: '🍦' },
    { en: 'fries', id: 'kentang goreng', emoji: '🍟' },
    { en: 'popcorn', id: 'popcorn', emoji: '🍿' },
    { en: 'baby', id: 'bayi', emoji: '👶' },
    { en: 'boy', id: 'anak laki-laki', emoji: '👦' },
    { en: 'girl', id: 'anak perempuan', emoji: '👧' },
    { en: 'man', id: 'pria', emoji: '👨' },
    { en: 'woman', id: 'wanita', emoji: '👩' },
    { en: 'shirt', id: 'kemeja', emoji: '👕' },
    { en: 'pants', id: 'celana', emoji: '👖' },
    { en: 'dress', id: 'gaun', emoji: '👗' },
    { en: 'socks', id: 'kaus kaki', emoji: '🧦' },
    { en: 'jacket', id: 'jaket', emoji: '🧥' },
    { en: 'gloves', id: 'sarung tangan', emoji: '🧤' },
    { en: 'scarf', id: 'syal', emoji: '🧣' },
    { en: 'boots', id: 'sepatu bot', emoji: '👢' },
    { en: 'sun', id: 'matahari', emoji: '☀️' },
    { en: 'moon', id: 'bulan', emoji: '🌙' },
    { en: 'star', id: 'bintang', emoji: '⭐' },
    { en: 'sky', id: 'langit', emoji: '☁️' },
    { en: 'cloud', id: 'awan', emoji: '☁️' },
    { en: 'rain', id: 'hujan', emoji: '🌧️' },
    { en: 'tree', id: 'pohon', emoji: '🌳' },
    { en: 'flower', id: 'bunga', emoji: '🌸' },
    { en: 'grass', id: 'rumput', emoji: '🌿' },
    { en: 'leaf', id: 'daun', emoji: '🍃' },
    { en: 'stone', id: 'batu', emoji: '🪨' },
    { en: 'sand', id: 'pasir', emoji: '🏖️' },
    { en: 'snow', id: 'salju', emoji: '❄️' },
    { en: 'rainbow', id: 'pelangi', emoji: '🌈' },
    { en: 'wind', id: 'angin', emoji: '🌬️' },
    { en: 'fire', id: 'api', emoji: '🔥' },
    { en: 'earth', id: 'bumi', emoji: '🌍' },
    { en: 'wood', id: 'kayu', emoji: '🪵' },
    { en: 'seed', id: 'biji', emoji: '🌱' },
    { en: 'house', id: 'rumah', emoji: '🏠' },
    { en: 'name', id: 'nama', emoji: '🏷️' },
    { en: 'friend', id: 'teman', emoji: '🧑‍🤝‍🧑' },
    { en: 'family', id: 'keluarga', emoji: '👨‍👩‍👧‍👦' },
    { en: 'road', id: 'jalan', emoji: '🛣️' },
    { en: 'shop', id: 'toko', emoji: '🏪' },
    { en: 'food', id: 'makanan', emoji: '🍱' },
    { en: 'bull', id: 'banteng', emoji: '🐂' },
    { en: 'chick', id: 'anak ayam', emoji: '🐤' },
    { en: 'donkey', id: 'keledai', emoji: '🫏' },
    { en: 'hippo', id: 'kuda nil', emoji: '🦛' },
    { en: 'rhino', id: 'badak', emoji: '🦏' },
    { en: 'crocodile', id: 'buaya', emoji: '🐊' },
    { en: 'lizard', id: 'kadal', emoji: '🦎' },
    { en: 'dinosaur', id: 'dinosaurus', emoji: '🦕' },
    { en: 'dragon', id: 'naga', emoji: '🐉' },
    { en: 'unicorn', id: 'unicorn', emoji: '🦄' },
    { en: 'nest', id: 'sarang', emoji: '🪺' },
    { en: 'feather', id: 'bulu', emoji: '🪶' },
    { en: 'robot', id: 'robot', emoji: '🤖' },
    { en: 'rocket', id: 'roket', emoji: '🚀' },
    { en: 'bus', id: 'bus', emoji: '🚌' },
    { en: 'boat', id: 'perahu', emoji: '⛵' },
    { en: 'motorcycle', id: 'sepeda motor', emoji: '🏍️' },
    { en: 'taxi', id: 'taksi', emoji: '🚕' },
    { en: 'helicopter', id: 'helikopter', emoji: '🚁' },
    { en: 'truck', id: 'truk', emoji: '🚚' },
    { en: 'map', id: 'peta', emoji: '🗺️' },
    { en: 'flag', id: 'bendera', emoji: '🚩' },
    { en: 'world', id: 'dunia', emoji: '🌍' },
  ],
  sentences: [
    { en: 'The cat is small', id: 'Kucing itu kecil' },
    { en: 'I like apples', id: 'Saya suka apel' },
    { en: 'The fish swims', id: 'Ikan itu berenang' },
    { en: 'The book is new', id: 'Buku itu baru' },
    { en: 'My bag is red', id: 'Tasku berwarna merah' },
    { en: 'The bird can fly', id: 'Burung itu bisa terbang' },
    { en: 'The dog is big', id: 'Anjing itu besar' },
    { en: 'The bird sings', id: 'Burung itu bernyanyi' },
    { en: 'I have a cat', id: 'Saya punya kucing' },
    { en: 'We like fruit', id: 'Kami suka buah' },
    { en: 'She drinks water', id: 'Dia minum air' },
    { en: 'He reads a book', id: 'Dia membaca buku' },
    { en: 'The apple is red', id: 'Apel itu merah' },
    { en: 'My pencil is new', id: 'Pensilku baru' },
    { en: 'The sky is blue', id: 'Langit itu biru' },
    { en: 'The cow eats grass', id: 'Sapi itu makan rumput' },
    { en: 'The sun is hot', id: 'Matahari itu panas' },
    { en: 'I see a star', id: 'Saya melihat bintang' },
    { en: 'The baby is happy', id: 'Bayi itu senang' },
    { en: 'My shoes are black', id: 'Sepatu saya hitam' },
    { en: 'The tree is tall', id: 'Pohon itu tinggi' },
    { en: 'The cat drinks milk', id: 'Kucing itu minum susu' },
    { en: 'I like my school', id: 'Saya suka sekolah saya' },
    { en: 'The fish is in water', id: 'Ikan itu di dalam air' },
    { en: 'We eat rice', id: 'Kami makan nasi' },
    { en: 'The flower is pink', id: 'Bunga itu merah muda' },
    { en: 'The moon is bright', id: 'Bulan itu terang' },
    { en: 'The frog can jump', id: 'Katak itu bisa melompat' },
    { en: 'The table is clean', id: 'Meja itu bersih' },
    { en: 'The car is fast', id: 'Mobil itu cepat' },
  ],
};
