import { LEVEL_1 } from './english/level-1';
import { LEVEL_2 } from './english/level-2';
import { LEVEL_3 } from './english/level-3';
import { LEVEL_4 } from './english/level-4';
import type { EnglishLevel } from './english/types';

export type { EnglishLevel, SentenceItem, VocabItem } from './english/types';

export const ENGLISH_MODES: {
  id: 'sentence' | 'match' | 'listen';
  name: string;
  desc: string;
  emoji: string;
}[] = [
  { id: 'sentence', name: 'Susun Kalimat', desc: 'Susun kata jadi kalimat Inggris', emoji: '🧩' },
  { id: 'match', name: 'Jodoh Kartu', desc: 'Cocokkan kata Inggris dan Indonesia', emoji: '🃏' },
  { id: 'listen', name: 'Dengar & Pilih', desc: 'Dengarkan kata, pilih artinya', emoji: '👂' },
];

export const ENGLISH_LEVELS: EnglishLevel[] = [LEVEL_1, LEVEL_2, LEVEL_3, LEVEL_4];

export const DISTRACTOR_WORDS = [
  'the',
  'a',
  'an',
  'this',
  'that',
  'these',
  'those',
  'some',
  'any',
  'every',
  'in',
  'on',
  'at',
  'to',
  'from',
  'with',
  'under',
  'over',
  'above',
  'behind',
  'near',
  'into',
  'across',
  'through',
  'along',
  'and',
  'or',
  'but',
  'because',
  'when',
  'before',
  'after',
  'while',
  'i',
  'you',
  'we',
  'they',
  'he',
  'she',
  'it',
  'my',
  'your',
  'his',
  'her',
  'our',
  'their',
  'me',
  'us',
  'them',
  'is',
  'are',
  'was',
  'were',
  'am',
  'be',
  'do',
  'does',
  'did',
  'can',
  'will',
  'has',
  'have',
  'had',
  'go',
  'goes',
  'eat',
  'eats',
  'drink',
  'drinks',
  'like',
  'likes',
  'love',
  'loves',
  'want',
  'wants',
  'need',
  'needs',
  'see',
  'sees',
  'look',
  'make',
  'makes',
  'take',
  'get',
  'put',
  'play',
  'plays',
  'read',
  'reads',
  'write',
  'writes',
  'run',
  'runs',
  'walk',
  'walks',
  'sleep',
  'sleeps',
  'help',
  'helps',
  'give',
  'gives',
  'big',
  'small',
  'new',
  'old',
  'good',
  'bad',
  'happy',
  'sad',
  'hot',
  'cold',
  'red',
  'blue',
  'green',
  'yellow',
  'beautiful',
  'funny',
  'kind',
  'very',
  'too',
  'always',
  'never',
  'often',
  'sometimes',
  'here',
  'there',
  'now',
  'today',
  'tomorrow',
  'yesterday',
  'again',
  'also',
  'only',
  'just',
  'not',
  'cat',
  'dog',
  'book',
  'ball',
  'house',
  'school',
  'water',
  'food',
  'friend',
  'family',
  'day',
  'night',
  'morning',
  'evening',
  'mother',
  'father',
  'boy',
  'girl',
  'man',
  'woman',
];

export function getEnglishLevel(level: number): EnglishLevel {
  return ENGLISH_LEVELS.find((item) => item.id === level) ?? ENGLISH_LEVELS[0];
}
